# Generated by Django 5.1.3 on 2024-11-19 13:42

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_employee'),
    ]

    operations = [
        migrations.CreateModel(
            name='Places',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=100)),
                ('image_url', models.ImageField(blank=True, null=True, upload_to=api.models.upload_to)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
